import { genkit, z, embedderRef } from 'genkit';
import { genkitPlugin } from 'genkit/plugin';
import { googleAI, vertexAI } from '@genkit-ai/google-genai';

import { initializeApp, applicationDefault } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { vertexAIVectorSearch, getFirestoreDocumentIndexer, getFirestoreDocumentRetriever, vertexAiIndexerRef, vertexAiRetrieverRef } from '@genkit-ai/vertexai/vectorsearch';

import { defineTurboQuantEmbedder } from 'genkit-turboquant-embedder/turboquant-embedder';
import { Document } from 'genkit/retriever';

// Initialize Firebase Admin strictly via your local gcloud application-default credentials
const app = initializeApp();
export const firestore = getFirestore(app);

// Wraps our C++ Custom Embedder into a Genkit Lifecycle Plugin so it registers early
const turboQuantPlugin = () => genkitPlugin('turboquant', async (ai) => {
  defineTurboQuantEmbedder(ai);
});

const ai = genkit({
  plugins: [
    googleAI(),
    turboQuantPlugin(),
    vertexAI({ location: 'us-central1' }),
    vertexAIVectorSearch({
      projectId: 'gen-lang-client-0174438926',
      location: 'us-central1',
      vectorSearchOptions: [
        {
          indexId: '7258916392949252096',
          indexEndpointId: '2831191863988322304',
          deployedIndexId: 'turboquant_demo_stream',
          publicDomainName: '1766812135.us-central1-288385349250.vdb.vertexai.goog',
          documentRetriever: getFirestoreDocumentRetriever(firestore, 'User_Chats'),
          documentIndexer: getFirestoreDocumentIndexer(firestore, 'User_Chats'),
          embedder: embedderRef({
            name: 'turboquant/compressor',
            info: { dimensions: 768, supports: { input: ['text'] } }
          }),
          embedderOptions: { baseEmbedder: 'vertexai/text-embedding-005' }
        }
      ]
    })
  ],
});

// Register custom TurboQuant embedder natively wrapping Google Gemini
export const turboQuantEmbedder = embedderRef({
  name: 'turboquant/compressor',
  info: { dimensions: 768, supports: { input: ['text'] } }
});

export const chatHistoryIndexer = vertexAiIndexerRef({ indexId: '7258916392949252096' });
export const chatHistoryRetriever = vertexAiRetrieverRef({ indexId: '7258916392949252096' });

let isPluginsInitialized = false;
export const chatFlow = ai.defineFlow(
  {
    name: 'chatFlow',
    inputSchema: z.object({
      userId: z.string(),
      userMessage: z.string(),
      shortTermMemory: z.array(z.string()).optional()
    }),
    outputSchema: z.object({
      answer: z.string(),
      savings: z.object({
        originalBytes: z.number(),
        compressedBytes: z.number(),
        bytesSaved: z.number()
      })
    }),
    streamSchema: z.string(),
  },
  async ({ userId, userMessage, shortTermMemory }, { sendChunk }) => {

    await (ai as any).registry.initializeAllPlugins();

    // 1. Retrieve the historical chat messages via RAG using TurboQuant Embeddings
    const relevantDocs = await ai.retrieve({
      retriever: chatHistoryRetriever,
      query: { content: [{ text: userMessage }] },
      options: {
        k: 10
      },
    });

    // 2. Generate response using retrieved history and short-term array
    const { response, stream } = ai.generateStream({
      model: googleAI.model('gemini-2.5-flash'),
      prompt: `
        You are a helpful AI assistant. Answer the user properly.
        
        [LONG-TERM VECTOR RECALLED MEMORY]
        Here are fragments of highly relevant past context recalled automatically from the database:
        ${relevantDocs.map(d => `- ${d.text}`).join('\n')}

        [SHORT-TERM CONVERSATION HISTORY]
        Here is the chronological immediate context of the current conversation:
        ${shortTermMemory?.map(m => `- ${m}`).join('\n') || 'None'}
        
        Recent User Message: ${userMessage}
      `,
      docs: relevantDocs
    });

    for await (const chunk of stream) {
      sendChunk(chunk.text);
    }

    const { text: responseText } = await response;

    // To harvest the exact mathematical data generated by our plugin before indexing,
    // we explicitly run the text through our Embedder middleware:
    const baseEmbedderOpt = googleAI.embedder('gemini-embedding-001');
    const texts = [`USER: ${userMessage}`, `AI: ${responseText}`];

    const embedResponse = await ai.embedMany({
      embedder: turboQuantEmbedder,
      content: texts,
      options: { baseEmbedder: baseEmbedderOpt }
    });

    let originalBytes = 0;
    let compressedBytes = 0;

    // We package the pre-computed arrays back into standard Documents and map our fetched metadata
    const docsToIndex = embedResponse.map((res, idx) => {
      const stats = (res as any).metadata?.turboQuantStats;
      if (stats) {
        originalBytes += stats.originalBytes;
        compressedBytes += stats.compressedBytes;
      }
      return Document.fromText(texts[idx], { userId, turboQuantStats: stats });
    });

    // 3. Persist the conversation snippet into Vectors via standard Genkit Indexer
    // We rely on the local vectorstore's defined embedder configuration to handle this natively
    await ai.index({
      indexer: chatHistoryIndexer,
      documents: docsToIndex
    });

    return {
      answer: responseText,
      savings: {
        originalBytes,
        compressedBytes,
        bytesSaved: originalBytes - compressedBytes
      }
    };
  }
);
